### ISSUE TITLE
操作系统版本不同会打不开？

### ISSUE THREAD

**Issue by huansu** [Fafa-DL/Image-Augmentation#1]
我用的win11，咋打不开呢？
是因为操作系统版本问题吗？

**Comment by huansu** [comment]
打开了，淦，只是稍微有点慢

**Comment by Fafa-DL** [comment]
我用win10做的，身边没有win11电脑暂时无法测试。此外V2.0版本要更新了，全新适配分类｜检测｜分割，可以关注我b站即将更新的视频。
------------------ 原始邮件 ------------------
发件人: huansu ***@***.***&gt;
发送时间: 2022年2月28日 10:12
收件人: Fafa-DL/Image-Augmentation ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Fafa-DL/Image-Augmentation] 操作系统版本不同会打不开？ (Issue #1)
