### ISSUE TITLE
关于xml文件格式不同导致的log日志中说anchor box is empty

### ISSUE THREAD

**Issue by jimuIee** [Fafa-DL/Image-Augmentation#10]
作者你好，我在改一个组图片的时候，log文件里报错空的anchor box，但是我检查了xml文件，有没有可能是格式不一致导致的，然后可能需要作者解决这种特殊情况

**Comment by jimuIee** [comment]
我检查了xml文件是有标注信息的

**Comment by Fafa-DL** [comment]
我在前一期视频有说明我是基于labelimg输出的xml进行的增强，如果有问题应该是格式不对应，你是什么格式可以贴在这

**Comment by jimuIee** [comment]
> 

作者你好，我发你邮箱了

**Comment by jimuIee** [comment]
> 我在前一期视频有说明我是基于labelimg输出的xml进行的增强，如果有问题应该是格式不对应，你是什么格式可以贴在这

作者你好，我发你qq邮箱了

**Comment by Fafa-DL** [comment]
> > 我在前一期视频有说明我是基于labelimg输出的xml进行的增强，如果有问题应该是格式不对应，你是什么格式可以贴在这
> 
> 
> 
> 作者你好，我发你qq邮箱了
> 
> 

不好意思比较忙，我看了下你的应该不是labelimg格式所以有误，如果你这种格式需要的人多可以考虑集成
