### ISSUE TITLE
请问教程中此处亮度改变是在范围中取一个随机值吗？

### ISSUE THREAD

**Issue by Grenaf** [Fafa-DL/Image-Augmentation#12]
![image](https://user-images.githubusercontent.com/73221711/204495976-73320aff-ab62-4da3-b675-9fb5a16f898e.png)

**Comment by Fafa-DL** [comment]
是的，若想固定亮度，仅给出固定值即可

**Comment by Grenaf** [comment]
> 是的，若想固定亮度，仅给出固定值即可

up反馈一个软件问题，当批量修改图片时修改的图像存储已完成，但进度条重新开始了
![image](https://user-images.githubusercontent.com/73221711/204796706-3c0419f1-122d-4af2-87cd-977fab814ab1.png)

**Comment by Fafa-DL** [comment]
> > 是的，若想固定亮度，仅给出固定值即可
> 
> up反馈一个软件问题，当批量修改图片时修改的图像存储已完成，但进度条重新开始了 ![image](https://user-images.githubusercontent.com/73221711/204796706-3c0419f1-122d-4af2-87cd-977fab814ab1.png)

我刚刚测试好像没这个问题，可以具体说说吗

**Comment by Grenaf** [comment]
环境：测试图片共700张，每张分辨率3000x3000左右，windows10系统，数据增强软件版本V3.2
操作：仅修改图片，文件夹路径如上图所示，起始编号缺省(保留原有文件名称)
问题：当亮度改变完成后，去到保存路径下生成了一个img文件夹，img文件夹下放置增强后的图片，当进度条超过百分之99时第一轮结束，通过查看img下属增强图片已增强完成，然后进度条重新开始了(没有跳出视频教程已完成界面)。

**Comment by Grenaf** [comment]
经过测试我的路径设置有问题(中文路径不支持，也不能正常结束)，当选择图像文件夹路径和选择保存路径一致时会出现该问题，并且log报错2022-12-01 21:05:18,243 - ERROR:  : type not support, only JPG, PNG, JPEG, TIF, TIFF, PPM, BMP, PGM are supported，但图像格式是jpg的还是汇报这个错误，当我修改路径不一致时则没有这个问题了。
![image](https://user-images.githubusercontent.com/73221711/205063974-915b227b-ae17-4fe7-8b72-52bf136437c4.png)
