### ISSUE TITLE
3.3版本生成的图片和xml文件名都有两个点

### ISSUE THREAD

**Issue by Adonis2018** [Fafa-DL/Image-Augmentation#16]
首先感谢up主的图像增强软件，真的太方便了，但是目前3.3版本生成的图片和xml文件名都有两个点，比如图片名是000001..jpg。不过幸亏3.2版本的没有这个问题，希望今后的版本能优化一下。

**Comment by Fafa-DL** [comment]
hello，我刚刚这里操作没这个问题，可以附上你详细的操作流程帮助check

**Comment by 969149731** [comment]
你好，我测试的3.3版本遇到了一样的问题，生成的文件都有2个点

**Comment by 969149731** [comment]
你好，我测试的3.3版本遇到了一样的问题，生成的文件都有2个点

**Comment by Fafa-DL** [comment]
> 你好，我测试的3.3版本遇到了一样的问题，生成的文件都有2个点

我刚刚拿测试用例测试没这个问题呀，奇怪了

**Comment by Fafa-DL** [comment]
> 你好，我测试的3.3版本遇到了一样的问题，生成的文件都有2个点

该问题已修复

**Comment by Fafa-DL** [comment]
> 首先感谢up主的图像增强软件，真的太方便了，但是目前3.3版本生成的图片和xml文件名都有两个点，比如图片名是000001..jpg。不过幸亏3.2版本的没有这个问题，希望今后的版本能优化一下。

该问题已修复，原来是新序号输出方式这一块出的bug。以后提issue可以尽量贴全操作步骤及报错~

**Comment by 969149731** [comment]
> > 你好，我测试的3.3版本遇到了一样的问题，生成的文件都有2个点
> 
> 该问题已修复

好的，up辛苦了！
