### ISSUE TITLE
3.2版本输出实例分割json文件失败

### ISSUE THREAD

**Issue by Jasonvon** [Fafa-DL/Image-Augmentation#18]
报错提示

`Tranceback (most recent call last):
File "ImaAug3.1.py", line 213, in run
TypeError: 'int' object is not subscriptable`

**Comment by Fafa-DL** [comment]
报错帖全呗，做到尽量完全能复现这个error

**Comment by Fafa-DL** [comment]
报错帖全呗，使用的版本、自己数据文件结构及组织形式、全部报错信息等，方便追溯问题

**Comment by Jasonvon** [comment]
文件组织形式和示例的不同，我的points是一个整型列表[x1, y1, x2, y2 ... xn, yn]，示例的是坐标对的列表[[x1, y1], [x2, y2] ... [xn, yn]]，估计是这个问题
