### ISSUE TITLE
2.5和3.3json生成失败

### ISSUE THREAD

**Issue by gnmtdt** [Fafa-DL/Image-Augmentation#20]
感谢大佬的项目
是用labelimg生成的json文件，如果进行带标注增强的话会直接闪退，没有报错记录，后台截图下来是这样的
Traceback (most recent call last) :
  File"ImgAug3.1.py", line 205, in run
TypeError : list indices must be integers or slices，not str
如果不带json文件，单纯图片是可以批量增强的，感谢

**Comment by Fafa-DL** [comment]
贴一下你的json格式

**Comment by gnmtdt** [comment]
[{"image": "1.png", "annotations": [{"label": "false", "coordinates": {"x": 33.08637469586376, "y": 35.27007299270075, "width": 20.0, "height": 21.000000000000004}}, {"label": "false", "coordinates": {"x": 69.58637469586375, "y": 10.770072992700744, "width": 16.999999999999993, "height": 18.0}}, {"label": "false", "coordinates": {"x": 35.08637469586376, "y": 89.27007299270075, "width": 18.0, "height": 19.0}}, {"label": "false", "coordinates": {"x": 69.58637469586375, "y": 114.27007299270075, "width": 18.999999999999993, "height": 21.0}}]}]

**Comment by LambitigousZ** [comment]
同问

**Comment by Fafa-DL** [comment]
json目前只支持labelImg标出来的格式，具体可参考我提供的json数据
