### ISSUE TITLE
程序报错，闪退。

### ISSUE THREAD

**Issue by 969149731** [Fafa-DL/Image-Augmentation#21]
![error](https://user-images.githubusercontent.com/84119169/236768463-c138e5be-39db-4196-aac5-670681b5d02c.PNG)

使用这个命令的时候会报错闪退：aug = iaa.Snowflakes(flake_size=(0.1, 0.4), speed=(0.01, 0.05))
请作者试试，麻烦了

**Comment by 969149731** [comment]
有一些命令是可以用的，但是好多增强方式都会闪退，测试了几个，有的行，有的不行

**Comment by Fafa-DL** [comment]
感谢反馈，已修复，请更新[V3.4](https://github.com/Fafa-DL/Image-Augmentation/releases/download/V3.4/ImgAug3.4.exe)
