### ISSUE TITLE
V3.0增强旋转数据集（标注文件是roLabelimg标注的xml文件）闪退

### ISSUE THREAD

**Issue by clcllllll** [Fafa-DL/Image-Augmentation#23]
标注旋转数据集时候，做图像增强时点击批量处理图片立即闪退。
![image](https://github.com/Fafa-DL/Image-Augmentation/assets/59495443/0826b64c-3f89-41dc-9482-14812c85f66b)
这是我旋转数据集的标注文件。
使用的增强语句是
`iaa.Affine(translate_percent={"x": (-0.2, 0.2), "y": (-0.2, 0.2)})
iaa.Affine(rotate=(-45, 45))`
![da316c9bf207c0bd923ca328b2f2a8c](https://github.com/Fafa-DL/Image-Augmentation/assets/59495443/81ded613-a9c9-49f6-8443-3e455f24d003)

**Comment by Fafa-DL** [comment]
你的xml和我支持的格式不一样呀，你看看我提供的data示例，所以报错找不到坐标
