### ISSUE TITLE
numpy的bool属性和bool_属性不兼容，闪退

### ISSUE THREAD

**Issue by qhqqhh** [Fafa-DL/Image-Augmentation#24]
<img width="744" alt="微信图片_20230708215252" src="https://github.com/Fafa-DL/Image-Augmentation/assets/89175092/547b1171-8ce6-4136-ac5a-2378d684c3df">
导可以看看这个链接：[https://blog.csdn.net/weixin_44716485/article/details/130554982](url)；这个问题经常遇到，也有人提过issue,我在本地降低numpy版本无效，可能需要修改源码。

**Comment by Fafa-DL** [comment]
hello，是不是B站私信过我？这个涉及的增强方式是什么

**Comment by cmjkqyl** [comment]
> hello，是不是B站私信过我？这个涉及的增强方式是什么

我也遇到了同样的问题。涉及到的增强方法是各种池化。

**Comment by Fafa-DL** [comment]
感谢反馈，已修复，请更新[V3.4](https://github.com/Fafa-DL/Image-Augmentation/releases/download/V3.4/ImgAug3.4.exe)
