### ISSUE TITLE
一人血书可以设置扩充目标检测数据倍数输入 ，现在只能一次一次扩充

### ISSUE THREAD

**Issue by yuninn** [Fafa-DL/Image-Augmentation#28]
感谢up!

**Comment by Fafa-DL** [comment]
没明白什么意思呀

**Comment by yuninn** [comment]
> 没明白什么意思呀

就是现在目标检测数据集是一倍的扩充 能不能输入一个参数 比如10 直接进行随机的10倍扩充

**Comment by yuninn** [comment]
> 没明白什么意思呀

就是现在目标检测数据集是一倍的扩充 能不能输入一个参数 比如10 直接进行随机的10倍增强
