### ISSUE TITLE
需要提供github的账户密码才能用？如何保证账户安全？

### ISSUE THREAD

**Issue by monkeycc** [Fafa-DL/Image-Augmentation#3]
需要提供github的账户密码才能用？如何保证账户安全？

**Comment by Fafa-DL** [comment]
没有这个说法啊，你是用其他软件下载的吧，直接默认用浏览器在GitHub的release下载是没问题的。或者可以在我的网盘中进行下载。

------------------ 原始邮件 ------------------
发件人: monkeycc ***@***.***&gt;
发送时间: 2022年7月2日 11:39
收件人: Fafa-DL/Image-Augmentation ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Fafa-DL/Image-Augmentation] 需要提供github的账户密码才能用？如何保证账户安全？ (Issue #3)





 
需要提供github的账户密码才能用？如何保证账户安全？

**Comment by monkeycc** [comment]
https://www.bilibili.com/video/BV1gZ4y1C7Ex

没注意看视频
原来有固定的账户和密码
