### ISSUE TITLE
生成图像标签没有对应的变换

### ISSUE THREAD

**Issue by pyl62112991** [Fafa-DL/Image-Augmentation#30]
采用此命令
iaa.Sequential([
    iaa.Affine(scale={"x": (0.5, 1.5), "y": (0.5, 1.5)}),
    iaa.WithColorspace(
    to_colorspace="HSV",
    from_colorspace="RGB",
    children=iaa.WithChannels(
        0,
        iaa.Add((0, 50))
    )
)
])

![963E70FA-61A5-42e9-83DB-6BFB02C23BBD](https://github.com/Fafa-DL/Image-Augmentation/assets/47971541/2410a233-fd53-44a2-88af-993ce7efe1a2)

**Comment by Fafa-DL** [comment]
可以将该例原始图像和label发送至516451964@qq.com（记得写明来由），有空我看看什么情况

**Comment by Fafa-DL** [comment]
原始这张图像的label是正常的吗？
