### ISSUE TITLE
报错：#请确认批量操作方式

### ISSUE THREAD

**Issue by wsgnay** [Fafa-DL/Image-Augmentation#31]
![image](https://github.com/Fafa-DL/Image-Augmentation/assets/51869494/c5c2d5ff-1645-4888-8fb9-94290020b56f)
![image](https://github.com/Fafa-DL/Image-Augmentation/assets/51869494/36bca4c1-0814-479c-ab4d-88be6003081c)
![image](https://github.com/Fafa-DL/Image-Augmentation/assets/51869494/713e1080-b4e5-4f5a-8e49-675f0931efc8)
软件报错，log里说是文件格式不支持，但是我的图片就是jpg啊，求回复

**Comment by wsgnay** [comment]
加载单张图片的话是正常的

**Comment by Fafa-DL** [comment]
**仅批量修改图片**和**XML**不要同时勾选
