### ISSUE TITLE
高斯模糊崩溃

### ISSUE THREAD

**Issue by SmithKevin0** [Fafa-DL/Image-Augmentation#35]
3.4版本在使用高斯模糊功能的时候黑框里显示'MainWin' object has no attribute 'xml_batch'
然后程序崩溃退出

![微信图片_20231214150229](https://github.com/Fafa-DL/Image-Augmentation/assets/82325324/eee3ac63-fdd9-4996-876f-967369c9030f)

**Comment by SmithKevin0** [comment]
是高斯噪声，刚刚使用motion blur也出现了同样的问题

**Comment by Fafa-DL** [comment]
把增强的方法发在这

**Comment by Fafa-DL** [comment]
已修复，请下载最新[V3.4](https://github.com/Fafa-DL/Image-Augmentation/releases/download/V3.4/ImgAug3.4.exe)版本
