### ISSUE TITLE
请问一操作就闪退是什么原因

### ISSUE THREAD

**Issue by Rosaline511** [Fafa-DL/Image-Augmentation#39]
第一次使用正常，关掉后再打开就一直闪退了，用的代码里自带的几个数据

**Comment by Fafa-DL** [comment]
日志有报错吗

**Comment by Rosaline511** [comment]
没有报错


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fafa-DL/Image-Augmentation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月9日(星期二) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fafa-DL/Image-Augmentation] 请问一操作就闪退是什么原因 (Issue #39)





 
日志有报错吗

**Comment by Rosaline511** [comment]
作者您好，我重新下载之后，又可以用了，可能是我电脑的问题，软件本身应该是没问题的，谢谢您的回复。

**Comment by Fafa-DL** [comment]
第一次使用正常然后就不行了，不应该啊，同样的操作同样的数据复现一遍呢？

**Comment by Rosaline511** [comment]
我重新下载软件之后现在已经正常啦，可能是我的电脑出了问题，谢谢作者大大！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Fafa ***@***.***&gt;; 
发送时间: 2024年1月10日(星期三) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fafa-DL/Image-Augmentation] 请问一操作就闪退是什么原因 (Issue #39)





 
第一次使用正常然后就不行了，不应该啊，同样的操作同样的数据复现一遍呢？
