### ISSUE TITLE
一点批量操作就闪退

### ISSUE THREAD

**Issue by jiubie89** [Fafa-DL/Image-Augmentation#40]
之前还能用，昨天到今天试了好几个版本，换了好几个电脑发现都会闪退

**Comment by jiubie89** [comment]
报错后很快就闪退了，我截屏了下来：
![5a299804f2a887094d4487962d0c0c7](https://github.com/Fafa-DL/Image-Augmentation/assets/149553348/1b8adda3-e373-4cd9-94a9-cdd9c972bfff)

**Comment by jiubie89** [comment]
是在批量json文件的同步增强的时候

**Comment by Fafa-DL** [comment]
utf-8的问题先排查是否存在中文
