### ISSUE TITLE
关于2.5版本的bug

### ISSUE THREAD

**Issue by KXHH2021** [Fafa-DL/Image-Augmentation#43]
你好，我使用前面的增强效果都没问题，使用到ColTemp增强效果时会闪退，我的数据集格式是png，仅批量处理图像。报错：Expected number of channels to be three, got 4 channels (shape (1080, 1920, 4)).

**Comment by KXHH2021** [comment]
我发现使用jpg格式的文件没有此问题，遇到这个问题可以把图片转为jpg格式的

**Comment by Fafa-DL** [comment]
2.5没有维护了呀
