### ISSUE TITLE
可视化标注这个如何使用？

### ISSUE THREAD

**Issue by StanleyYake** [Fafa-DL/Image-Augmentation#44]
您好，非常感谢这个数据增强软件，我有几个问题：
1.可视化标注这个如何使用；
2.针对图像分割任务，可以一起将标注后的多边形区域（Json）一起增强吗？

**Comment by pumpbumb** [comment]
> 您好，非常感谢这个数据增强软件，我有几个问题： 1.可视化标注这个如何使用； 2.针对图像分割任务，可以一起将标注后的多边形区域（Json）一起增强吗？

旋转后，标注文件位置都不对了😭

**Comment by Fafa-DL** [comment]
> 您好，非常感谢这个数据增强软件，我有几个问题： 1.可视化标注这个如何使用； 2.针对图像分割任务，可以一起将标注后的多边形区域（Json）一起增强吗？

1. 建议看我在B站发的视频教程
2. labelme出来的polygon会同步增强

**Comment by StanleyYake** [comment]
好的，找到了。我试试：https://www.bilibili.com/video/BV1gZ4y1C7Ex/?spm_id_from=333.788&vd_source=ac21d8c0a03fc2fb8f97051c4d37b644
