### ISSUE TITLE
3,4版本依然闪退

### ISSUE THREAD

**Issue by Zhangzeyu7** [Fafa-DL/Image-Augmentation#47]
3.4版本当运行：iaa.imgcorruptlike.GaussianBlur(severity=2)时，无论是单张测试还是批量运行，都会闪退

**Comment by Zhangzeyu7** [comment]
> 3.4版本当运行：iaa.imgcorruptlike.GaussianBlur(severity=2)时，无论是单张测试还是批量运行，都会闪退
已经自己解决

**Comment by Totoro-wen** [comment]
请问，怎么解决的
