### ISSUE TITLE
定向检测框旋转增强后，突出边界的检测框坐标异常

### ISSUE THREAD

**Issue by caopeizhi2** [Fafa-DL/Image-Augmentation#48]
在对yolov8-obb的定向检测框做数据增强时，旋转检测框的四个端点经过旋转后，如果检测框超出图像的边界，那超出图像边界的端点会直接收到边界处，导致检测框位置错误，不是矩形。
![图片1](https://github.com/Fafa-DL/Image-Augmentation/assets/112549688/704a0b55-cb95-4b82-ae22-43ec038b3f6d)

**Comment by Fafa-DL** [comment]
请提供该张数据以及增强方式，这样方便定位问题~
