### ISSUE TITLE
导，能不能加个txt格式标注的同步增强

### ISSUE THREAD

**Issue by YoRha19990213** [Fafa-DL/Image-Augmentation#6]

**Comment by Fafa-DL** [comment]
txt里什么格式？

**Comment by YoRha19990213** [comment]
yolo那种归一化的xywh的格式，我通过转xml再转回txt是解决了自己的问题，但是我觉得加上比较方便，还有发现了那个转换工具的bug，当我xml与txt互转的时候，xml的路径如果是。。。/xml/xxx 就会报错找不到路径，而改成。。。/xml 就能正常运行，可能是源码的问题

**Comment by Fafa-DL** [comment]
转换工具是用的我写的吗https://github.com/Fafa-DL/LabelConvert

**Comment by YoRha19990213** [comment]
是的

**Comment by Grenaf** [comment]
需求+1
