### ISSUE TITLE
批量操作，点击按钮后没有反应

### ISSUE THREAD

**Issue by haoshuiwuxiang** [Fafa-DL/Image-Augmentation#7]

**Comment by Fafa-DL** [comment]
可能是图片过多且增强方式复杂，等一等就有进度条了

**Comment by haoshuiwuxiang** [comment]
好哒，谢谢

从 Windows 版邮件发送

发件人: Fafa Bro
发送时间: 2022年11月18日 9:41
收件人: Fafa-DL/Image-Augmentation
抄送: haoshuiwuxiang; Author
主题: Re: [Fafa-DL/Image-Augmentation] 批量操作，点击按钮后没有反应 (Issue #7)

可能是图片过多且增强方式复杂，等一等就有进度条了
