### ISSUE TITLE
关于输出图像的名字保持不变

### ISSUE THREAD

**Issue by jimuIee** [Fafa-DL/Image-Augmentation#8]
作者你好，最近又用上了你的图像增强软件3.0，但是我有个问题就是增强后的图片名字能否保持，还是说暂时只能按照1-多少这么来的

**Comment by Fafa-DL** [comment]
由考虑这种情况，谢谢反馈，将提上议程~

**Comment by Fafa-DL** [comment]
最新的推送已经支持该功能

**Comment by Grenaf** [comment]
> 最新的推送已经支持该功能
期待能在V2.5版本上也实现这个功能，觉得V2版本简单好用。经过测试V3.2版本可以实现名称不被修改，虽然V3版本能自定义
Look forward to the V2.5 version to implement this feature, found the V2 version easy to use. The V3.2 version can be tested without the name being changed，although the V3 version can be customized
